-- Données de seed générées depuis le Google Sheet (à exécuter après schema.sql)

insert into challenges (id, nom, description, ordre_affichage) values
  ('marathon-4', 'Marathon 4', 'Programme progressif d''étirements et de travail postural, semaine après semaine.', 1)
on conflict (id) do nothing;

insert into exercises (id, challenge_id, semaine, jour, ordre, titre, video_id, duree_min, categorie, materiel, texte) values
  ('s1j1o1', 'marathon-4', 1, 1, 1, 'Jour 1 — Ouverture et respiration', 'lCdgp09q9RI', 11, 'étirements', 'Coussin', 'Séance d''introduction pour entrer en douceur dans la routine. Travail au sol, ouverture de la cage thoracique et respiration. Stabilisation du bassin. Un coussin sous les ischions aide à tenir la position 90-90 sans forcer.'),
  ('s1j2o2', 'marathon-4', 1, 2, 2, 'Jour 2 — Alignement du bassin', 'TxbmEp2XaxM', 11, 'étirements', 'Coussin', 'Attention portée à la position du bassin : éviter toute bascule, garder un axe neutre. Vigilance sur l''épaule si un appui du bras est utilisé. Respiration continue tout au long de la pratique.'),
  ('s1j3o3', 'marathon-4', 1, 3, 3, 'Jour 3 — Posture et engagement du bassin', 'FMMp_H3T89E', 11, 'étirements', 'Coussin', 'Travail sur la posture puis engagement progressif du bassin pour construire soutien et contrôle. Suivre attentivement les consignes techniques du guide vidéo.'),
  ('s1j4o4', 'marathon-4', 1, 4, 4, 'Jour 4 — Mobilité de la cage thoracique', 'dI7aPB2tDoc', 9, 'étirements', 'Coussin', 'La cage thoracique entre en jeu. Poursuite du travail sur le bassin avec le coussin en appui. Amélioration de la mobilité costale et étirements doux pour plus d''espace dans le corps.'),
  ('s1j5o5', 'marathon-4', 1, 5, 5, 'Jour 5 — Travail avec les balles', '6C8PwMqQAk0', 15, 'étirements', 'Myo balles, ballon', 'Premier travail en profondeur avec les balles. Maintenir un axe corporel clair, s''allonger continuellement, éviter la bascule du bassin, rester attentif à la respiration.'),
  ('s1j5o6', 'marathon-4', 1, 5, 6, 'Jour 5 (bonus) — Ouverture du diaphragme', '7wtl4KpG9aU', 3, 'étirements', 'Myo balles, ballon', 'Vidéo optionnelle au sol pour approfondir le travail du diaphragme.'),
  ('s1j6o7', 'marathon-4', 1, 6, 7, 'Jour 6 — Rouleau de mousse, bas du corps', 'I7IpEF4Lt_E', 14, 'étirements', 'Foam roller', 'Travail au sol avec un rouleau en mousse lisse (sans relief). Focus sur le bas du corps, le tractus ilio-tibial, la région pelvienne et les zones lymphatiques de l''aine.'),
  ('s2j1o8', 'marathon-4', 2, 1, 8, 'Semaine 2, jour 1 — Reconnexion et respiration', 'nkDxgTmJWO0', 15, 'étirements', '', 'Premier jour de la semaine 2. Restauration de la connexion au corps, activation des muscles profonds, régulation de la respiration. Attention à l''axe du corps : tête relevée, nuque allongée.'),
  ('s2j1o9', 'marathon-4', 2, 1, 9, 'Semaine 2, jour 1 (bonus) — Posture C7', 'xv3_v50B5O8', 4, 'étirements', 'Myo balles', 'Vidéo optionnelle mais recommandée. Travail avec la balle puis exercices de posture (vertèbre C7, exercice ''Frame'', exercice anti text-neck) à ajouter en fin de séance, environ 20 secondes chacun.'),
  ('s2j2o10', 'marathon-4', 2, 2, 10, 'Semaine 2, jour 2 — Cage thoracique et diaphragme', 'GvvEST4sNcA', 12, 'étirements', 'Bande de résistance, serviette', 'Libération de la cage thoracique et restauration d''une respiration diaphragmatique fonctionnelle. Améliore la circulation, la posture et le drainage lymphatique.'),
  ('s2j3o11', 'marathon-4', 2, 3, 11, 'Semaine 2, jour 3 — Bassin et fessiers', 'AxJ-mK9xoo8', 13, 'étirements', 'Myo balles', 'Travail des fessiers et des ischions pour relâcher les tensions chroniques qui impactent le bas du dos. Séance assise évoluant vers une activation musculaire plus profonde.'),
  ('s2j4o12', 'marathon-4', 2, 4, 12, 'Semaine 2, jour 4 — Mobilité costale et respiration ample', 'bxUoYTZ68ik', 12, 'étirements', 'Bande de résistance', 'Libération profonde de la cage thoracique, augmentation du volume inspiratoire, meilleure oxygénation des tissus grâce à une résistance ciblée avec la bande.'),
  ('s2j5o13', 'marathon-4', 2, 5, 13, 'Semaine 2, jour 5 — Bassin fonctionnel', 'r6IgERqq0yk', 18, 'étirements', 'Ballon', 'Travail pelvien profond pour améliorer la circulation, relâcher les tensions et restaurer la mécanique naturelle des hanches. Modifiable sur chaise ou au sol si besoin.'),
  ('s2j6o14', 'marathon-4', 2, 6, 14, 'Semaine 2, jour 6 — Bassin et gainage profond', 'x_D23olbIdA', 11, 'étirements', 'Ballon', 'Synchronisation pelvienne, mobilité des hanches et circulation. Activation abdominale profonde associée à la respiration pour renforcer le soutien interne.')
on conflict (id) do nothing;
